"""TD/Keldon training primitives for Magnate."""

from .ablation_manifest import (
    FrozenReplaySplit,
    count_jsonl_rows,
    named_files_content_sha256,
    replay_content_sha256,
    resolve_frozen_replay_split,
    sha256_file,
    write_replay_path_lists,
)
from .checkpoint import (
    TD_OPPONENT_CHECKPOINT_TYPE,
    TD_VALUE_CHECKPOINT_TYPE,
    load_opponent_checkpoint,
    load_value_checkpoint,
    save_opponent_checkpoint,
    save_value_checkpoint,
)
from .holdout import evaluate_opponent_holdout, evaluate_value_holdout
from .io import (
    read_opponent_samples_jsonl,
    read_opponent_samples_jsonl_many,
    read_value_transitions_jsonl,
    read_value_transitions_jsonl_many,
    write_opponent_samples_jsonl,
    write_value_transitions_jsonl,
)
from .models import OpponentModel, ValueNet
from .replay import OpponentReplayBuffer, ValueReplayBuffer
from .self_play import (
    SelfPlayEpisode,
    SelfPlayProgressCallback,
    collect_self_play_episode,
    collect_self_play_games,
    flatten_opponent_samples,
    flatten_value_transitions,
)
from .symmetry_augmentation import (
    DISTRICT_AUGMENTATION_MODES,
    DISTRICT_AUGMENTATION_NONE,
    DISTRICT_AUGMENTATION_S4,
    DISTRICT_AUGMENTATION_S4_ORBIT,
    PAWN_DISTRICT_PERMUTATIONS,
    PawnDistrictPermutation,
    ValueAugmentationBatch,
    augment_opponent_training_batch,
    augment_value_training_batch,
    derive_augmentation_stream_seed,
    inverse_pawn_district_permutation,
    opponent_augmentation_copies_per_sample,
    permute_encoded_action_features,
    permute_encoded_observation,
)
from .targets import n_step_bootstrap_targets, td_lambda_targets
from .train import (
    TD_VALUE_TARGET_MODE,
    TD_VALUE_TARGET_MODE_TD0,
    TD_VALUE_TARGET_MODE_TD_LAMBDA,
    TD_VALUE_TARGET_MODES,
    OpponentTrainConfig,
    OpponentTrainStepSummary,
    TDOpponentTrainer,
    TDTrainConfig,
    TDTrainStepSummary,
    TDValueTrainer,
    build_value_sequence_index,
    hard_sync,
    train_opponent_batch,
    train_value_batch,
)
from .types import OpponentSample, ValueTransition

__all__ = [
    "FrozenReplaySplit",
    "count_jsonl_rows",
    "named_files_content_sha256",
    "replay_content_sha256",
    "resolve_frozen_replay_split",
    "sha256_file",
    "write_replay_path_lists",
    "OpponentModel",
    "ValueNet",
    "OpponentReplayBuffer",
    "ValueReplayBuffer",
    "read_value_transitions_jsonl",
    "read_value_transitions_jsonl_many",
    "write_value_transitions_jsonl",
    "read_opponent_samples_jsonl",
    "read_opponent_samples_jsonl_many",
    "write_opponent_samples_jsonl",
    "evaluate_opponent_holdout",
    "evaluate_value_holdout",
    "SelfPlayEpisode",
    "SelfPlayProgressCallback",
    "collect_self_play_episode",
    "collect_self_play_games",
    "flatten_opponent_samples",
    "flatten_value_transitions",
    "n_step_bootstrap_targets",
    "td_lambda_targets",
    "DISTRICT_AUGMENTATION_MODES",
    "DISTRICT_AUGMENTATION_NONE",
    "DISTRICT_AUGMENTATION_S4",
    "DISTRICT_AUGMENTATION_S4_ORBIT",
    "PAWN_DISTRICT_PERMUTATIONS",
    "PawnDistrictPermutation",
    "ValueAugmentationBatch",
    "augment_opponent_training_batch",
    "augment_value_training_batch",
    "derive_augmentation_stream_seed",
    "inverse_pawn_district_permutation",
    "opponent_augmentation_copies_per_sample",
    "permute_encoded_action_features",
    "permute_encoded_observation",
    "TDTrainConfig",
    "TDTrainStepSummary",
    "TD_VALUE_TARGET_MODE",
    "TD_VALUE_TARGET_MODE_TD0",
    "TD_VALUE_TARGET_MODE_TD_LAMBDA",
    "TD_VALUE_TARGET_MODES",
    "OpponentTrainConfig",
    "OpponentTrainStepSummary",
    "TDValueTrainer",
    "TDOpponentTrainer",
    "build_value_sequence_index",
    "hard_sync",
    "train_value_batch",
    "train_opponent_batch",
    "OpponentSample",
    "ValueTransition",
    "TD_VALUE_CHECKPOINT_TYPE",
    "TD_OPPONENT_CHECKPOINT_TYPE",
    "save_value_checkpoint",
    "load_value_checkpoint",
    "save_opponent_checkpoint",
    "load_opponent_checkpoint",
]
